//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchnuppiDemoApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogData
    {
        public int ID { get; set; }
        public int DeviceID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string ProductionOrderNumber { get; set; }
        public string ProducerNumber { get; set; }
        public string SerialNumber { get; set; }
        public string TesterUserName { get; set; }
        public string MachineName { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
